[package]
name = "libcraft-core"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
vek = "0.14"
serde = { version = "1", features = ["derive"] }
strum = "0.20"
strum_macros = "0.20"
